In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("spam.csv")
df.head()

,Category,Message
0,ham,"Go until jurong point, crazy.. Available only ..."
1,ham,Ok lar... Joking wif u oni...
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...
3,ham,U dun say so early hor... U c already then say...
4,ham,"Nah I don't think he goes to usf, he lives aro..."


In [3]:
df.Category.value_counts()

Category
ham     4825
spam     747
Name: count, dtype: int64

In [4]:
def get_spam_number(x):
    if x == 'spam':
        return 1
    return 0

In [5]:
df['spam'] = df['Category'].apply(lambda x: 1 if x == 'spam' else 0)

In [6]:
df.head()

,Category,Message,spam
0,ham,"Go until jurong point, crazy.. Available only ...",0
1,ham,Ok lar... Joking wif u oni...,0
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...,1
3,ham,U dun say so early hor... U c already then say...,0
4,ham,"Nah I don't think he goes to usf, he lives aro...",0


In [7]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(df.Message, df.spam, test_size=0.2)

In [8]:
x_train.shape

(4457,)

In [9]:
x_test.shape

(1115,)

In [10]:
type(x_train)

pandas.core.series.Series

In [13]:
x_train[:4]

1399     No did you check? I got his detailed message now
3586    Heart is empty without love.. Mind is empty wi...
668                 This pay is  &lt;DECIMAL&gt;  lakhs:)
2373    Watching tv lor... Y she so funny we bluff her...
Name: Message, dtype: object

In [14]:
type(y_train)

pandas.core.series.Series

In [17]:
y_train[:5]

1399    0
3586    0
668     0
2373    0
2100    1
Name: spam, dtype: int64

In [20]:
from sklearn.feature_extraction.text import CountVectorizer

v = CountVectorizer()

x_train_cv = v.fit_transform(x_train.values)
x_train_cv

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 59352 stored elements and shape (4457, 7721)>

In [19]:
type(x_train.values)

numpy.ndarray

In [21]:
x_train_cv.toarray()[:2]

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], shape=(2, 7721))

In [22]:
x_train_cv.shape

(4457, 7721)

In [25]:
v.get_feature_names_out()[1000:1050]

array(['anyone', 'anyones', 'anyplaces', 'anythiing', 'anythin',
       'anything', 'anythingtomorrow', 'anytime', 'anyway', 'anyways',
       'anywhere', 'aom', 'apart', 'apartment', 'apes', 'apo',
       'apologetic', 'apologise', 'apologize', 'apology', 'app',
       'apparently', 'appeal', 'appear', 'appendix', 'applebees',
       'apples', 'application', 'apply', 'applying', 'appointment',
       'appointments', 'appreciate', 'appreciated', 'approaches',
       'approaching', 'appropriate', 'approve', 'approx', 'apps', 'appt',
       'appy', 'april', 'aproach', 'apt', 'aptitude', 'ar', 'arab',
       'arabian', 'arcade'], dtype=object)

In [27]:
v.get_feature_names_out().shape

(7721,)

In [28]:
dir(v)

['_CountVectorizer__metadata_request__fit',
 '_CountVectorizer__metadata_request__transform',
 '__annotations__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__firstlineno__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__sklearn_clone__',
 '__sklearn_tags__',
 '__static_attributes__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_char_ngrams',
 '_char_wb_ngrams',
 '_check_stop_words_consistency',
 '_check_vocabulary',
 '_count_vocab',
 '_doc_link_module',
 '_doc_link_template',
 '_doc_link_url_param_generator',
 '_get_class_level_metadata_request_values',
 '_get_doc_link',
 '_get_metadata_request',
 '_get_param_names',
 '_get_params_html',
 '_html_repr',
 '_limit_features',
 '_parameter_constraints',
 '_repr_html

In [29]:
v.vocabulary_

{'no': 4783,
 'did': 2302,
 'you': 7684,
 'check': 1751,
 'got': 3205,
 'his': 3443,
 'detailed': 2276,
 'message': 4443,
 'now': 4833,
 'heart': 3387,
 'is': 3746,
 'empty': 2581,
 'without': 7528,
 'love': 4222,
 'mind': 4473,
 'wisdom': 7514,
 'eyes': 2741,
 'dreams': 2440,
 'amp': 952,
 'life': 4096,
 'frnds': 3020,
 'so': 6255,
 'alwys': 935,
 'be': 1276,
 'in': 3644,
 'touch': 6971,
 'good': 3189,
 'night': 4765,
 'sweet': 6631,
 'this': 6826,
 'pay': 5106,
 'lt': 4244,
 'decimal': 2204,
 'gt': 3265,
 'lakhs': 3991,
 'watching': 7378,
 'tv': 7057,
 'lor': 4202,
 'she': 6053,
 'funny': 3054,
 'we': 7391,
 'bluff': 1415,
 'her': 3415,
 'wat': 7375,
 'izzit': 3770,
 'because': 1286,
 'thk': 6827,
 'it': 3756,
 'impossible': 3636,
 'between': 1338,
 'us': 7184,
 'sms': 6235,
 'services': 6010,
 'for': 2945,
 'your': 7688,
 'inclusive': 3653,
 'text': 6761,
 'credits': 2065,
 'pls': 5238,
 'goto': 3210,
 'www': 7619,
 'comuk': 1939,
 'net': 4731,
 'login': 4175,
 'unsubscribe': 7151,


In [31]:
x_train_np = x_train_cv.toarray()
x_train_np

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], shape=(4457, 7721))

In [34]:
x_train_np[0]

array([0, 0, 0, ..., 0, 0, 0], shape=(7721,))

In [35]:
np.where(x_train_np[0]!=0)

(array([1751, 2276, 2302, 3205, 3443, 4443, 4783, 4833, 7684]),)

In [40]:
x_train[:4][1399]

'No did you check? I got his detailed message now'

In [41]:
from sklearn.naive_bayes import MultinomialNB

model = MultinomialNB()
model.fit(x_train_cv, y_train)

,"alpha alpha: float or array-like of shape (n_features,), default=1.0Additive (Laplace/Lidstone) smoothing parameter(set alpha=0 and force_alpha=True, for no smoothing).",1.0
,"force_alpha force_alpha: bool, default=TrueIf False and alpha is less than 1e-10, it will set alpha to1e-10. If True, alpha will remain unchanged. This may causenumerical errors if alpha is too close to 0... versionadded:: 1.2.. versionchanged:: 1.4 The default value of `force_alpha` changed to `True`.",True
,"fit_prior fit_prior: bool, default=TrueWhether to learn class prior probabilities or not.If false, a uniform prior will be used.",True
,"class_prior class_prior: array-like of shape (n_classes,), default=NonePrior probabilities of the classes. If specified, the priors are notadjusted according to the data.",None


In [42]:
x_test_cv = v.transform(x_test)

In [45]:
from sklearn.metrics import classification_report

y_pred  = model.predict(x_test_cv)
classification_report(y_test, y_pred)

'              precision    recall  f1-score   support\n\n           0       0.99      1.00      0.99       952\n           1       0.99      0.94      0.97       163\n\n    accuracy                           0.99      1115\n   macro avg       0.99      0.97      0.98      1115\nweighted avg       0.99      0.99      0.99      1115\n'

In [46]:
emails = [
    'Hey mohan, can we get together to watch footbal game tomorrow?',
    'Upto 20% discount on parking, exclusive offer just for you. Dont miss this reward!'
]

emails_count = v.transform(emails)
model.predict(emails_count)

array([0, 1])

In [47]:
from sklearn.pipeline import Pipeline

clf = Pipeline([
    ('vectorizer', CountVectorizer()),
    ('nb', MultinomialNB())
])

In [48]:
clf.fit(x_train, y_train)

,"steps steps: list of tuplesList of (name of step, estimator) tuples that are to be chained insequential order. To be compatible with the scikit-learn API, all stepsmust define `fit`. All non-last steps must also define `transform`. See:ref:`Combining Estimators ` for more details.","[('vectorizer', ...), ('nb', ...)]"
,"transform_input transform_input: list of str, default=NoneThe names of the :term:`metadata` parameters that should be transformed by thepipeline before passing it to the step consuming it.This enables transforming some input arguments to ``fit`` (other than ``X``)to be transformed by the steps of the pipeline up to the step which requiresthem. Requirement is defined via :ref:`metadata routing `.For instance, this can be used to pass a validation set through the pipeline.You can only set this if metadata routing is enabled, which youcan enable using ``sklearn.set_config(enable_metadata_routing=True)``... versionadded:: 1.6",None
,"memory memory: str or object with the joblib.Memory interface, default=NoneUsed to cache the fitted transformers of the pipeline. The last stepwill never be cached, even if it is a transformer. By default, nocaching is performed. If a string is given, it is the path to thecaching directory. Enabling caching triggers a clone of the transformersbefore fitting. Therefore, the transformer instance given to thepipeline cannot be inspected directly. Use the attribute ``named_steps``or ``steps`` to inspect estimators within the pipeline. Caching thetransformers is advantageous when fitting is time consuming. See:ref:`sphx_glr_auto_examples_neighbors_plot_caching_nearest_neighbors.py`for an example on how to enable caching.",None
,"verbose verbose: bool, default=FalseIf True, the time elapsed while fitting each step will be printed as itis completed.",False
,"input input: {'filename', 'file', 'content'}, default='content'- If `'filename'`, the sequence passed as an argument to fit is expected to be a list of filenames that need reading to fetch the raw content to analyze.- If `'file'`, the sequence items must have a 'read' method (file-like object) that is called to fetch the bytes in memory.- If `'content'`, the input is expected to be a sequence of items that can be of type string or byte.",'content'
,"encoding encoding: str, default='utf-8'If bytes or files are given to analyze, this encoding is used todecode.",'utf-8'
,"decode_error decode_error: {'strict', 'ignore', 'replace'}, default='strict'Instruction on what to do if a byte sequence is given to analyze thatcontains characters not of the given `encoding`. By default, it is'strict', meaning that a UnicodeDecodeError will be raised. Othervalues are 'ignore' and 'replace'.",'strict'
,"strip_accents strip_accents: {'ascii', 'unicode'} or callable, default=NoneRemove accents and perform other character normalizationduring the preprocessing step.'ascii' is a fast method that only works on characters that havea direct ASCII mapping.'unicode' is a slightly slower method that works on any characters.None (default) means no character normalization is performed.Both 'ascii' and 'unicode' use NFKD normalization from:func:`unicodedata.normalize`.",None
,"lowercase lowercase: bool, default=TrueConvert all characters to lowercase before tokenizing.",True
,"preprocessor preprocessor: callable, default=NoneOverride the preprocessing (strip_accents and lowercase) stage whilepreserving the tokenizing and n-grams generation steps.Only applies if ``analyzer`` is not callable.",None
,"tokenizer tokenizer: callable, default=NoneOverride the string tokenization step while preserving thepreprocessing and n-grams generation steps.Only applies if ``analyzer == 'word'``.",None


In [49]:
y_pred = clf.predict(x_test)

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.99      1.00      0.99       952
           1       0.99      0.94      0.97       163

    accuracy                           0.99      1115
   macro avg       0.99      0.97      0.98      1115
weighted avg       0.99      0.99      0.99      1115

