In [1]:
import numpy as np

In [2]:
np.__version__

'2.2.6'

In [3]:
np.array([1,3,5,7])

array([1, 3, 5, 7])

In [4]:
arr1 = np.array([1,3,5,7])

In [5]:
type(arr1)

numpy.ndarray

In [6]:
id(arr1)

2262770662544

In [7]:
arr2 = np.array([1,3,5,7])

In [8]:
id(arr2)

2263142845488

In [9]:
arr3 = arr1

In [10]:
print(id(arr1))
print(id(arr3))

2262770662544
2262770662544


In [11]:
# if we want to copy only values
arr4 = np.copy(arr1)

print(id(arr1))
print(id(arr4))

2262770662544
2263142845296


In [17]:
## creating array with tuples

In [14]:
type((1,3,5,7,9))

tuple

In [15]:
np.array((1,3,5,7,9))

array([1, 3, 5, 7, 9])

In [18]:
type((1,3,5,7))

tuple

In [19]:
np.array((1,3,5,7))

array([1, 3, 5, 7])

In [20]:
## creating array with dictonary

In [21]:
type({'one':1,'two':2,'three':3})

dict

In [22]:
np.array({'one':1,'two':2,'three':3})

array({'one': 1, 'two': 2, 'three': 3}, dtype=object)

In [23]:
## creating array with Sets

In [24]:
{1,1,1,2,2,2,3,3,5}

{1, 2, 3, 5}

In [25]:
type({1,1,1,2,2,2,3,3,5})

set

In [26]:
np.array({1,1,1,2,2,2,3,3,5})

array({1, 2, 3, 5}, dtype=object)

In [27]:
## creating array with a range

In [28]:
[i for i in range(10)]

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [29]:
[i for i in np.arange(10)]

[np.int64(0),
 np.int64(1),
 np.int64(2),
 np.int64(3),
 np.int64(4),
 np.int64(5),
 np.int64(6),
 np.int64(7),
 np.int64(8),
 np.int64(9)]

In [30]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [32]:
np.arange(1,10,3)

array([1, 4, 7])

In [33]:
len10 = np.arange(10)

In [34]:
len(len10)

10

In [35]:
len10.size

10

In [37]:
np.array([111,2.3,True])

array([111. ,   2.3,   1. ])

In [38]:
arr5 = np.array([111,2.3,True])

In [39]:
type(arr5[0])

numpy.float64

In [40]:
arr6 = np.array([111,2.3,'Hi'])

In [41]:
type(arr6)

numpy.ndarray

In [42]:
type(arr6[0])

numpy.str_

In [43]:
## Data type of numPy array

In [46]:
np.array(['apple','banana','strawberry'])

array(['apple', 'banana', 'strawberry'], dtype='<U10')

In [47]:
arr7 = np.array(['apple','banana','strawberry'])

In [48]:
type(arr7[0])

numpy.str_

In [49]:
## Creating array with linspace function

In [54]:
np.linspace(1,10,5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [55]:
np.linspace(-10,10,20)

array([-10.        ,  -8.94736842,  -7.89473684,  -6.84210526,
        -5.78947368,  -4.73684211,  -3.68421053,  -2.63157895,
        -1.57894737,  -0.52631579,   0.52631579,   1.57894737,
         2.63157895,   3.68421053,   4.73684211,   5.78947368,
         6.84210526,   7.89473684,   8.94736842,  10.        ])

In [56]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [57]:
np.ones(5)

array([1., 1., 1., 1., 1.])