In [1]:
## multidimentional arrays

In [2]:
li1 = [[1,2,3],[4,5,6],[7,8,9]]

In [3]:
li1[0][0]

1

In [5]:
import numpy as np
np.array(li1)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
arr2d = np.array(li1)

In [7]:
arr2d.ndim

2

In [8]:
## 3D array

In [9]:
np.array([[[1,2],[3,4]],[[5,6],[7,8]]])

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [10]:
arr3d = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])

In [11]:
arr3d.ndim

3

In [12]:
arr3d[0][0]

array([1, 2])

In [14]:
arr3d[0][0][1]

np.int64(2)

In [15]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [16]:
arr2dzeros = np.zeros((2,3), dtype='int64')

In [17]:
type(arr2dzeros)

numpy.ndarray

In [18]:
type(arr2dzeros[0][0])

numpy.int64

In [19]:
arr2dzeros

array([[0, 0, 0],
       [0, 0, 0]])

In [20]:
arr2dzeros.astype('float32')

array([[0., 0., 0.],
       [0., 0., 0.]], dtype=float32)